# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2021-08-27T12:09:44+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
